#-------------------------------
# General Site Settings

title: Timtographer
email: TimothyTChin@gmail.com

menu:
- {name: Portfolio, link: '#portfolio'}
- {name: About, link: '#about'}
- {name: Contact, link: '#contact'}


#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X


#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Hero Section

hero:
  hero-title:

social:
  - {icon: "ti-instagram", link: "https://instagram.com/timtographer"}
  - {icon: "ti-linkedin", link: "https://www.linkedin.com/in/timothytchin/"}
  - {icon: "ti-facebook", link: "https://fb.me/timtographer"}
  - {icon: "ti-twitter", link: "https://twitter.com/chinspecial"}


#-------------------------------
# About (Section and Page)

# About Section
blurb:
  Hi, my name is Tim. I make photographs and videos.

blurb-btn-link: '#about'
blurb-btn-name: About me


# About Page
about-me:
  I am a software engineer turned photographer and videographer. I've always had creative interests in photography and videography and recently decided to take the next step in my life toward making my passion into a full time career. I still have a lot to learn and improve, but I'm constantly looking for ways to better myself and my craft. Thanks for visiting and please reach out if there's anything you think I might be able to help you with.

#-------------------------------
# Experience Section

experience-title: Experience And Education
experience:
- {name: Software Engineer, icon: 'icon-1.png', date: 'September 2015 - May 2020', organization: 'Storygize', link: 'https://storygize.com'}
- {name: Founder/Engineer, icon: 'icon-2.png', date: 'September 2014 - September 2015', organization: 'Hapaxity'}


#-------------------------------
# Education Section

education-title: Education
education:
- {name: 'B.S. Computer Engineering', date: '2013', organization: 'University of California Santa Barbara'}

#-------------------------------
# Services Section

services-title: Services
services:
- {
    name: Videography,
    icon: ti-video-camera,
    description: 'Film, edit, and produce high quality video content for a wide variety of client types',
    active: # Add true to select section
  }
- {
    name: Photography,
    icon: ti-camera,
    description: 'Beautiful and refined photographs of natural landscapes, food, art, and anything else interesting',
    active: true # Add true to select section
  }
- {
    name: Web Design,
    icon: ti-panel,
    description: 'Elegantly crafted websites for businesses or individuals of all kinds',
    active: # Add true to select section
  }


# Portfolio Page
portfolio-label:
- {
    title : "LANDSCAPE",
    type : "landscape"
  }
- {
    title : "FOOD",
    type : "food"
  }
- {
    title : "NATURE",
    type : "nature"
  }

portfolio-items:
  - image : "assets/images/photo/landscape/boat_girl.jpg"
    url: "#"
    portfolio-type:
     - type: "landscape"
     - type: "nature"

  - image : "assets/images/photo/landscape/chinese_garden.jpg"
    url: "#"
    portfolio-type:
     - type: "landscape"
     - type: "nature"

  - image : "assets/images/photo/landscape/dome_bros_crop.jpg"
    url: "#"
    portfolio-type:
     - type: "landscape"
     - type: "nature"

  - image : "assets/images/photo/landscape/monolith.jpg"
    url: "#"
    portfolio-type:
     - type: "landscape"
     - type: "nature"

  - image : "assets/images/photo/landscape/night_bloom.jpg"
    url: "#"
    portfolio-type:
     - type: "landscape"
     - type: "nature"

  - image : "assets/images/photo/landscape/night_wires.jpg"
    url: "#"
    portfolio-type:
     - type: "landscape"
     - type: "nature"

  - image : "assets/images/photo/landscape/north_dome.jpg"
    url: "#"
    portfolio-type:
     - type: "landscape"
     - type: "nature"

  - image : "assets/images/photo/landscape/overlook.jpg"
    url: "#"
    portfolio-type:
     - type: "landscape"
     - type: "nature"

  - image : "assets/images/photo/landscape/pdx_sunset.jpg"
    url: "#"
    portfolio-type:
     - type: "landscape"
     - type: "nature"

  - image : "assets/images/photo/landscape/steps.jpg"
    url: "#"
    portfolio-type:
     - type: "landscape"
     - type: "nature"

  - image : "assets/images/photo/landscape/suburb_sunset.jpg"
    url: "#"
    portfolio-type:
     - type: "landscape"
     - type: "nature"

  - image : "assets/images/photo/landscape/sunset2.jpg"
    url: "#"
    portfolio-type:
     - type: "landscape"
     - type: "nature"

  - image : "assets/images/photo/landscape/sunset3.jpg"
    url: "#"
    portfolio-type:
     - type: "landscape"
     - type: "nature"

  - image : "assets/images/photo/landscape/trail_sunset.jpg"
    url: "#"
    portfolio-type:
     - type: "landscape"
     - type: "nature"

  - image : "assets/images/photo/food/afuri_ramen.jpg"
    url: "#"
    portfolio-type:
     - type: "food"

  - image : "assets/images/photo/food/benedict.jpg"
    url: "#"
    portfolio-type:
     - type: "food"

  - image : "assets/images/photo/food/calamari.jpg"
    url: "#"
    portfolio-type:
     - type: "food"

  - image : "assets/images/photo/food/chicken_waffle.jpg"
    url: "#"
    portfolio-type:
     - type: "food"

  - image : "assets/images/photo/food/dough.jpg"
    url: "#"
    portfolio-type:
     - type: "food"

  - image : "assets/images/photo/food/fries.jpg"
    url: "#"
    portfolio-type:
     - type: "food"

  - image : "assets/images/photo/food/gyoza.jpg"
    url: "#"
    portfolio-type:
     - type: "food"

  - image : "assets/images/photo/food/karaage.jpg"
    url: "#"
    portfolio-type:
     - type: "food"

  - image : "assets/images/photo/food/melon_pan.jpg"
    url: "#"
    portfolio-type:
     - type: "food"

  - image : "assets/images/photo/food/oxtail_dip.jpg"
    url: "#"
    portfolio-type:
     - type: "food"

  - image : "assets/images/photo/food/pizza.jpg"
    url: "#"
    portfolio-type:
     - type: "food"

  - image : "assets/images/photo/food/porkbelly_mac.jpg"
    url: "#"
    portfolio-type:
     - type: "food"


#client-slider-items:
#  - logo: "assets/images/clients-logo/client-logo-1.png"
#    url: "#"
#
#  - logo: "assets/images/clients-logo/client-logo-2.png"
#    url: "#"
#
#  - logo: "assets/images/clients-logo/client-logo-3.png"
#    url: "#"
#
#  - logo: "assets/images/clients-logo/client-logo-4.png"
#    url: "#"
#
#  - logo: "assets/images/clients-logo/client-logo-5.png"
#    url: "#"
#
#  - logo: "assets/images/clients-logo/client-logo-1.png"
#    url: "#"
#
#  - logo: "assets/images/clients-logo/client-logo-2.png"
#    url: "#"
#
#  - logo: "assets/images/clients-logo/client-logo-3.png"
#    url: "#"
#
#  - logo: "assets/images/clients-logo/client-logo-4.png"
#    url: "#"
#
#  - logo: "assets/images/clients-logo/client-logo-5.png"
#    url: "#"


#-------------------------------
# Contact Section

contact-title: Contact
contact-email: TimothyTChin@gmail.com