#-------------------------------
# General Site Settings

title: Timtographer
email: TimothyTChin@gmail.com

menu:
- {name: Portfolio, link: '#portfolio'}
- {name: About, link: '#about'}
- {name: Contact, link: '#contact'}


#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X


#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Hero Section

hero:
  hero-title:

social:
- {icon: "ti-facebook", link: "http://fb.me/timtographer"}
- {icon: "ti-instagram", link: "http://instagram.com/timtographer"}
- {icon: "ti-twitter", link: "http://twitter.com/chinspecial"}


#-------------------------------
# About (Section and Page)

# About Section
blurb:
  Hi, my name is Tim. I make photographs and videos.

blurb-btn-link: '#about'
blurb-btn-name: About me


# About Page
about-me:
  My name is Tim and I am a software engineer turned photographer and videographer. I've always had creative interests in photography and videography and recently decided to take the next step in my life toward making my passion into a full time career. I still have a lot to learn and improve, but I'm constantly looking for ways to better myself and my craft. Thanks for visiting and reach out if there's anything you think I might be able to help you with.

# Work Process Section
work-process:
  - title : "Research and Plan"
    icon : "assets/images/icons/plan.png"
    content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
    
  - title : "Design and Develop"
    icon : "assets/images/icons/design.png"
    content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
    
  - title : "Deliver"
    icon : "assets/images/icons/print.png"
    content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."


#-------------------------------
# Skills Section

skills-title: Skills
skills:
- {name: Photography, color: '#fdb157', value: '90%'}
- {name: Editing, color: '#bdecf6', value: '80%'}
- {name: Videography, color: '#9473e6', value: '70%'}
- {name: Engineering, color: '#ffbcaa', value: '90%'}


#-------------------------------
# Experience Section

experience-title: Experience And Education
experience:
- {name: Software Engineer, icon: 'icon-1.png', date: 'September 2015 - May 2020', organization: 'Storygize', link: 'https://storygize.com'}
- {name: Founder/Engineer, icon: 'icon-2.png', date: 'September 2014 - September 2015', organization: 'Hapaxity'}


#-------------------------------
# Education Section

education-title: Education
education:
- {name: B.S. Computer Engineering, date: '2013', organization: 'University of California Santa Barbara'}

#-------------------------------
# Services Section

services-title: Services
services:
- {
    name: Videography,
    icon: ti-video-camera,
    description: 'Film, edit, and produce high quality video content for a wide variety of client types',
    active: # Add true to select section
  }
- {
    name: Photography,
    icon: ti-camera,
    description: 'Beautiful and refined photographs of natural landscapes, food, art, and anything else interesting',
    active: true # Add true to select section
  }
- {
    name: Web Design,
    icon: ti-panel,
    description: 'Elegantly crafted website showcases for any kind of businesses or individuals',
    active: # Add true to select section
  }



#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
portfolio-home-items:
  - image : "assets/images/portfolio/item-1.png"
    url: "#"

  - image : "assets/images/portfolio/item-2.png"
    url: "#"

  - image : "assets/images/portfolio/item-3.png"
    url: "#"

  - image : "assets/images/portfolio/item-4.png"
    url: "#"

  - image : "assets/images/portfolio/item-5.png"
    url: "#"


# Portfolio Page
portfolio-label:
- {
    title : "UI/UX Design",
    type : "design"
  }
- {
    title : "BRANDING",
    type : "branding"
  }
- {
    title : "ILLUSTRATION",
    type : "illustration"
  }

portfolio-items:
  - image : "assets/images/portfolio/item-1.png"
    url: "#"
    portfolio-type:
     - type: "design"
     - type: "illustration"
      
  - image : "assets/images/portfolio/item-2.png"
    url: "#"
    portfolio-type:
      - type: "branding"
      
  - image : "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "illustration"
      
  - image : "assets/images/portfolio/item-6.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "branding"
      
  - image : "assets/images/portfolio/item-8.png"
    url: "#"
    portfolio-type:
      - type: "illustration"
      
  - image : "assets/images/portfolio/item-5.png"
    url: "#"
    portfolio-type:
      - type: "design"
      
  - image : "assets/images/portfolio/item-1.png"
    url: "#"
    portfolio-type:
      - type: "branding"
      
  - image : "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "illustration"
      - type: "branding"
      
  - image : "assets/images/portfolio/item-7.png"
    url: "#"
    portfolio-type:
      - type: "illustration"

#-------------------------------
# Contact Section

contact-title: Contact Info
contact-email: TimothyTChin@gmail.com