#-------------------------------
# General Site Settings

title: Timtographer
email: TimothyTChin@gmail.com

menu:
- {name: Portfolio, link: '#portfolio'}
- {name: About, link: '#about'}
- {name: Contact, link: '#contact'}


#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X


#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Hero Section

hero:
  hero-title:

social:
  - {icon: "ti-instagram", link: "https://instagram.com/timtographer"}
  - {icon: "ti-linkedin", link: "https://www.linkedin.com/in/timothytchin/"}
  - {icon: "ti-facebook", link: "https://fb.me/timtographer"}
  - {icon: "ti-twitter", link: "https://twitter.com/chinspecial"}


#-------------------------------
# About (Section and Page)

# About Section
blurb:
  Hi, my name is Tim. I make photographs and videos.

blurb-btn-link: '#about'
blurb-btn-name: About me


# About Page
about-me:
  I am a software engineer turned photographer and videographer. I've always had creative interests in photography and videography and recently decided to take the next step in my life toward making my passion into a full time career. I still have a lot to learn and improve, but I'm constantly looking for ways to better myself and my craft. Thanks for visiting and please reach out if there's anything you think I might be able to help you with.

#-------------------------------
# Experience Section

experience-title: Experience And Education
experience:
- {name: Software Engineer, icon: 'icon-2.png', date: 'September 2015 - May 2020', organization: 'Storygize', link: 'https://storygize.com'}
- {name: Founder/Engineer, icon: 'icon-1.png', date: 'September 2014 - September 2015', organization: 'Hapaxity'}


#-------------------------------
# Education Section

education-title: Education
education:
- {name: 'B.S. Computer Engineering', date: '2013', organization: 'University of California Santa Barbara'}

#-------------------------------
# Services Section

services-title: Services
services:
- {
    name: Videography,
    icon: ti-video-camera,
    description: 'Film, edit, and produce high quality video content for a wide variety of client types',
    active: # Add true to select section
  }
- {
    name: Photography,
    icon: ti-camera,
    description: 'Beautiful and refined photographs of natural landscapes, food, art, and anything else interesting',
    active: true # Add true to select section
  }
- {
    name: Web Design,
    icon: ti-panel,
    description: 'Elegantly crafted websites for businesses or individuals of all kinds',
    active: # Add true to select section
  }


# Portfolio Page
portfolio-label:
- {
    title : "LANDSCAPE",
    type : "landscape"
  }
- {
    title : "FOOD",
    type : "food"
  }
- {
    title : "NATURE",
    type : "nature"
  }
- {
    title : "STREET",
    type : "street"
  }
- {
    title : "MISC",
    type : "misc"
  }

#####  Landscape Images

portfolio-items:
  - image : "assets/images/photo/landscape/boat_girl.jpg"
    thumb_image : "assets/images/photo/thumb/boat_girl.jpg"
    url: "#"
    portfolio-type:
     - type: "landscape"
     - type: "nature"

  - image : "assets/images/photo/landscape/chinese_garden.jpg"
    thumb_image : "assets/images/photo/thumb/chinese_garden.jpg"
    url: "#"
    portfolio-type:
     - type: "landscape"
     - type: "nature"

  - image : "assets/images/photo/landscape/dome_bros_crop.jpg"
    thumb_image : "assets/images/photo/thumb/dome_bros_crop.jpg"
    url: "#"
    portfolio-type:
     - type: "landscape"
     - type: "nature"

  - image : "assets/images/photo/landscape/monolith.jpg"
    thumb_image : "assets/images/photo/thumb/monolith.jpg"
    url: "#"
    portfolio-type:
     - type: "landscape"
     - type: "nature"

  - image : "assets/images/photo/landscape/night_bloom.jpg"
    thumb_image : "assets/images/photo/thumb/night_bloom.jpg"
    url: "#"
    portfolio-type:
     - type: "landscape"
     - type: "nature"

  - image : "assets/images/photo/landscape/night_wires.jpg"
    thumb_image : "assets/images/photo/thumb/night_wires.jpg"
    url: "#"
    portfolio-type:
     - type: "landscape"
     - type: "nature"

  - image : "assets/images/photo/landscape/north_dome.jpg"
    thumb_image : "assets/images/photo/thumb/north_dome.jpg"
    url: "#"
    portfolio-type:
     - type: "landscape"
     - type: "nature"

  - image : "assets/images/photo/landscape/overlook.jpg"
    thumb_image : "assets/images/photo/thumb/overlook.jpg"
    url: "#"
    portfolio-type:
     - type: "landscape"
     - type: "nature"

  - image : "assets/images/photo/landscape/pdx_sunset.jpg"
    thumb_image : "assets/images/photo/thumb/pdx_sunset.jpg"
    url: "#"
    portfolio-type:
     - type: "landscape"
     - type: "nature"

  - image : "assets/images/photo/landscape/steps.jpg"
    thumb_image : "assets/images/photo/thumb/steps.jpg"
    url: "#"
    portfolio-type:
     - type: "landscape"
     - type: "nature"

  - image : "assets/images/photo/landscape/suburb_sunset.jpg"
    thumb_image : "assets/images/photo/thumb/suburb_sunset.jpg"
    url: "#"
    portfolio-type:
     - type: "landscape"
     - type: "nature"

  - image : "assets/images/photo/landscape/sunset2.jpg"
    thumb_image : "assets/images/photo/thumb/sunset2.jpg"
    url: "#"
    portfolio-type:
     - type: "landscape"
     - type: "nature"

  - image : "assets/images/photo/landscape/sunset3.jpg"
    thumb_image : "assets/images/photo/thumb/sunset3.jpg"
    url: "#"
    portfolio-type:
     - type: "landscape"
     - type: "nature"

  - image : "assets/images/photo/landscape/trail_sunset.jpg"
    thumb_image : "assets/images/photo/thumb/trail_sunset.jpg"
    url: "#"
    portfolio-type:
     - type: "landscape"
     - type: "nature"

#####  Food Images
  - image : "assets/images/photo/food/afuri_ramen.jpg"
    thumb_image : "assets/images/photo/thumb/afuri_ramen.jpg"
    url: "#"
    portfolio-type:
     - type: "food"

  - image : "assets/images/photo/food/benedict.jpg"
    thumb_image : "assets/images/photo/thumb/benedict.jpg"
    url: "#"
    portfolio-type:
     - type: "food"

  - image : "assets/images/photo/food/calamari.jpg"
    thumb_image : "assets/images/photo/thumb/calamari.jpg"
    url: "#"
    portfolio-type:
     - type: "food"

  - image : "assets/images/photo/food/chicken_waffle.jpg"
    thumb_image : "assets/images/photo/thumb/chicken_waffle.jpg"
    url: "#"
    portfolio-type:
     - type: "food"

  - image : "assets/images/photo/food/dough.jpg"
    thumb_image : "assets/images/photo/thumb/dough.jpg"
    url: "#"
    portfolio-type:
     - type: "food"

  - image : "assets/images/photo/food/fries.jpg"
    thumb_image : "assets/images/photo/thumb/fries.jpg"
    url: "#"
    portfolio-type:
     - type: "food"

  - image : "assets/images/photo/food/gyoza.jpg"
    thumb_image : "assets/images/photo/thumb/gyoza.jpg"
    url: "#"
    portfolio-type:
     - type: "food"

  - image : "assets/images/photo/food/karaage.jpg"
    thumb_image : "assets/images/photo/thumb/karaage.jpg"
    url: "#"
    portfolio-type:
     - type: "food"

  - image : "assets/images/photo/food/melon_pan.jpg"
    thumb_image : "assets/images/photo/thumb/melon_pan.jpg"
    url: "#"
    portfolio-type:
     - type: "food"

  - image : "assets/images/photo/food/oxtail_dip.jpg"
    thumb_image : "assets/images/photo/thumb/oxtail_dip.jpg"
    url: "#"
    portfolio-type:
     - type: "food"

  - image : "assets/images/photo/food/pizza.jpg"
    thumb_image : "assets/images/photo/thumb/pizza.jpg"
    url: "#"
    portfolio-type:
     - type: "food"

  - image : "assets/images/photo/food/porkbelly_mac.jpg"
    thumb_image : "assets/images/photo/thumb/porkbelly_mac.jpg"
    url: "#"
    portfolio-type:
     - type: "food"

#####  Nature Images
  - image: "assets/images/photo/nature/bee1.jpg"
    thumb_image: "assets/images/photo/thumb/bee1.jpg"
    url: "#"
    portfolio-type:
      - type: "nature"

  - image: "assets/images/photo/nature/bee2.jpg"
    thumb_image: "assets/images/photo/thumb/bee2.jpg"
    url: "#"
    portfolio-type:
      - type: "nature"

  - image: "assets/images/photo/nature/bonsai.jpg"
    thumb_image: "assets/images/photo/thumb/bonsai.jpg"
    url: "#"
    portfolio-type:
      - type: "nature"

  - image: "assets/images/photo/nature/criss_cross.jpg"
    thumb_image: "assets/images/photo/thumb/criss_cross.jpg"
    url: "#"
    portfolio-type:
      - type: "nature"
      - type: "landscape"

  - image: "assets/images/photo/nature/fallen_tree.jpg"
    thumb_image: "assets/images/photo/thumb/fallen_tree.jpg"
    url: "#"
    portfolio-type:
      - type: "nature"
      - type: "landscape"

  - image: "assets/images/photo/nature/glow.jpg"
    thumb_image: "assets/images/photo/thumb/glow.jpg"
    url: "#"
    portfolio-type:
      - type: "nature"
      - type: "landscape"

  - image: "assets/images/photo/nature/glow2.jpg"
    thumb_image: "assets/images/photo/thumb/glow2.jpg"
    url: "#"
    portfolio-type:
      - type: "nature"
      - type: "landscape"

  - image: "assets/images/photo/nature/green_beetle.jpg"
    thumb_image: "assets/images/photo/thumb/green_beetle.jpg"
    url: "#"
    portfolio-type:
      - type: "nature"

  - image: "assets/images/photo/nature/lotus.jpg"
    thumb_image: "assets/images/photo/thumb/lotus.jpg"
    url: "#"
    portfolio-type:
      - type: "nature"
      - type: "landscape"

  - image: "assets/images/photo/nature/macro_blue.jpg"
    thumb_image: "assets/images/photo/thumb/macro_blue.jpg"
    url: "#"
    portfolio-type:
      - type: "nature"

  - image: "assets/images/photo/nature/macro_green.jpg"
    thumb_image: "assets/images/photo/thumb/macro_green.jpg"
    url: "#"
    portfolio-type:
      - type: "nature"

  - image: "assets/images/photo/nature/macro_purple.jpg"
    thumb_image: "assets/images/photo/thumb/macro_purple.jpg"
    url: "#"
    portfolio-type:
      - type: "nature"

  - image: "assets/images/photo/nature/macro_white.jpg"
    thumb_image: "assets/images/photo/thumb/macro_white.jpg"
    url: "#"
    portfolio-type:
      - type: "nature"

  - image: "assets/images/photo/nature/macro_yellow.jpg"
    thumb_image: "assets/images/photo/thumb/macro_yellow.jpg"
    url: "#"
    portfolio-type:
      - type: "nature"

  - image: "assets/images/photo/nature/macro_yellow_close.jpg"
    thumb_image: "assets/images/photo/thumb/macro_yellow_close.jpg"
    url: "#"
    portfolio-type:
      - type: "nature"

  - image: "assets/images/photo/nature/mantis1.jpg"
    thumb_image: "assets/images/photo/thumb/mantis1.jpg"
    url: "#"
    portfolio-type:
      - type: "nature"

  - image: "assets/images/photo/nature/pink_blossom.jpg"
    thumb_image: "assets/images/photo/thumb/pink_blossom.jpg"
    url: "#"
    portfolio-type:
      - type: "nature"

  - image: "assets/images/photo/nature/succulent.jpg"
    thumb_image: "assets/images/photo/thumb/succulent.jpg"
    url: "#"
    portfolio-type:
      - type: "nature"

  - image: "assets/images/photo/nature/succulent2.jpg"
    thumb_image: "assets/images/photo/thumb/succulent2.jpg"
    url: "#"
    portfolio-type:
      - type: "nature"

  - image: "assets/images/photo/nature/white_bloom.jpg"
    thumb_image: "assets/images/photo/thumb/white_bloom.jpg"
    url: "#"
    portfolio-type:
      - type: "nature"
      - type: "landscape"

  - image: "assets/images/photo/nature/white_blossom.jpg"
    thumb_image: "assets/images/photo/thumb/white_blossom.jpg"
    url: "#"
    portfolio-type:
      - type: "nature"
      - type: "landscape"

  - image: "assets/images/photo/nature/white_blossom2.jpg"
    thumb_image: "assets/images/photo/thumb/white_blossom2.jpg"
    url: "#"
    portfolio-type:
      - type: "nature"
      - type: "landscape"

  - image: "assets/images/photo/nature/white_blossom_small.jpg"
    thumb_image: "assets/images/photo/thumb/white_blossom_small.jpg"
    url: "#"
    portfolio-type:
      - type: "nature"

#####  Misc Images

  - image : "assets/images/photo/misc/tokai.jpg"
    thumb_image : "assets/images/photo/thumb/tokai.jpg"
    url: "#"
    portfolio-type:
      - type: "misc"

  - image : "assets/images/photo/misc/trains.jpg"
    thumb_image : "assets/images/photo/thumb/trains.jpg"
    url: "#"
    portfolio-type:
      - type: "misc"

  - image : "assets/images/photo/misc/yellow_train.jpg"
    thumb_image : "assets/images/photo/thumb/yellow_train.jpg"
    url: "#"
    portfolio-type:
      - type: "misc"

######  Storefront images

  - image : "assets/images/photo/storefront/afuri.jpg"
    thumb_image : "assets/images/photo/thumb/afuri.jpg"
    url: "#"
    portfolio-type:
      - type: "misc"
      - type: "food"
      - type: "street"

  - image: "assets/images/photo/storefront/hat_yai.jpg"
    thumb_image: "assets/images/photo/thumb/hat_yai.jpg"
    url: "#"
    portfolio-type:
      - type: "misc"
      - type: "food"

  - image : "assets/images/photo/storefront/hat_yai2.jpg"
    thumb_image: "assets/images/photo/thumb/hat_yai2.jpg"
    url: "#"
    portfolio-type:
      - type: "misc"
      - type: "food"
      - type: "street"

  - image: "assets/images/photo/storefront/hat_yai3.jpg"
    thumb_image: "assets/images/photo/thumb/hat_yai3.jpg"
    url: "#"
    portfolio-type:
      - type: "misc"
      - type: "food"

  - image: "assets/images/photo/storefront/hat_yai4.jpg"
    thumb_image: "assets/images/photo/thumb/hat_yai4.jpg"
    url: "#"
    portfolio-type:
      - type: "misc"
      - type: "food"

  - image: "assets/images/photo/storefront/hollywood-theater.jpg"
    thumb_image: "assets/images/photo/thumb/hollywood-theater.jpg"
    url: "#"
    portfolio-type:
      - type: "misc"
      - type: "street"

  - image: "assets/images/photo/storefront/little_big_burger.jpg"
    thumb_image: "assets/images/photo/thumb/little_big_burger.jpg"
    url: "#"
    portfolio-type:
      - type: "misc"
      - type: "food"
      - type: "street"

  - image: "assets/images/photo/storefront/voodoo.jpg"
    thumb_image: "assets/images/photo/thumb/voodoo.jpg"
    url: "#"
    portfolio-type:
      - type: "misc"
      - type: "food"
      - type: "street"

#####  Street

  - image: "assets/images/photo/street/chestnuts.jpg"
    thumb_image: "assets/images/photo/thumb/chestnuts.jpg"
    url: "#"
    portfolio-type:
      - type: "street"
      - type: "food"

  - image: "assets/images/photo/street/chillin.jpg"
    thumb_image: "assets/images/photo/thumb/chillin.jpg"
    url: "#"
    portfolio-type:
      - type: "street"

  - image: "assets/images/photo/street/emoji.jpg"
    thumb_image: "assets/images/photo/thumb/emoji.jpg"
    url: "#"
    portfolio-type:
      - type: "street"
      - type: "misc"

  - image: "assets/images/photo/street/lacma_lights.jpg"
    thumb_image: "assets/images/photo/thumb/lacma_lights.jpg"
    url: "#"
    portfolio-type:
      - type: "street"
      - type: "misc"

  - image: "assets/images/photo/street/pike_place.jpg"
    thumb_image: "assets/images/photo/thumb/pike_place.jpg"
    url: "#"
    portfolio-type:
      - type: "street"

  - image: "assets/images/photo/street/piroshky.jpg"
    thumb_image: "assets/images/photo/thumb/piroshky.jpg"
    url: "#"
    portfolio-type:
      - type: "street"

  - image: "assets/images/photo/street/red.jpg"
    thumb_image: "assets/images/photo/thumb/red.jpg"
    url: "#"
    portfolio-type:
      - type: "street"

  - image: "assets/images/photo/street/steam.jpg"
    thumb_image: "assets/images/photo/thumb/steam.jpg"
    url: "#"
    portfolio-type:
      - type: "street"

  - image: "assets/images/photo/street/sun_drum.jpg"
    thumb_image: "assets/images/photo/thumb/sun_drum.jpg"
    url: "#"
    portfolio-type:
      - type: "street"

  - image: "assets/images/photo/street/tired.jpg"
    thumb_image: "assets/images/photo/thumb/tired.jpg"
    url: "#"
    portfolio-type:
      - type: "street"

  - image: "assets/images/photo/street/tram.jpg"
    thumb_image: "assets/images/photo/thumb/tram.jpg"
    url: "#"
    portfolio-type:
      - type: "street"
      - type: "misc"

#client-slider-items:
#  - logo: "assets/images/clients-logo/client-logo-1.png"
#    url: "#"
#
#  - logo: "assets/images/clients-logo/client-logo-2.png"
#    url: "#"
#
#  - logo: "assets/images/clients-logo/client-logo-3.png"
#    url: "#"
#
#  - logo: "assets/images/clients-logo/client-logo-4.png"
#    url: "#"
#
#  - logo: "assets/images/clients-logo/client-logo-5.png"
#    url: "#"
#
#  - logo: "assets/images/clients-logo/client-logo-1.png"
#    url: "#"
#
#  - logo: "assets/images/clients-logo/client-logo-2.png"
#    url: "#"
#
#  - logo: "assets/images/clients-logo/client-logo-3.png"
#    url: "#"
#
#  - logo: "assets/images/clients-logo/client-logo-4.png"
#    url: "#"
#
#  - logo: "assets/images/clients-logo/client-logo-5.png"
#    url: "#"


#-------------------------------
# Contact Section

contact-title: Contact
contact-email: TimothyTChin@gmail.com